
- name: check exim4 version
  shell: "dpkg -l exim4 | grep '^ii' | awk '{print $3}'"
  register: eximversion

- debug: var=eximversion

- name: install nullmailer
  apt:
          name: nullmailer
          state: present
  when: eximversion["stdout"] != "4.89-2+deb9u3"

- name: purge exim-packages
  apt:
          name: "{{ packages }}"
          purge: yes
          state: absent
  vars:
          packages:
                  - exim4
                  - exim4-base 
                  - exim4-config
                  - exim4-daemon-light
  when: eximversion["stdout"] != "4.89-2+deb9u3"

- name: install vulnerable exim-packages
  apt:
          name: "{{ packages }}"
          state: present
  vars:
          packages:
                  - exim4
                  - exim4-daemon-heavy

- name: configure mailname
  copy:
          dest: /etc/mailname
          content: |
                  {{exim_mailname}}

- name: create exim4.conf.template
  template:
          src: exim4.conf.template.j2
          dest: /etc/exim4/exim4.conf.template
          force: yes

- name: create update-exim4.conf.conf
  template:
          src: update-exim4.conf.j2
          dest: /etc/exim4/update-exim4.conf.conf
  notify: update-exim4.conf

- name: add mailname to hosts
  lineinfile:
          dest: /etc/hosts
          regexp: '.*{{item}}$'
          line: '{{item}}'
  with_items:
          - "{{exim_ip}} {{exim_mailname}} {{exim_maildomain}}"
  when: exim_update_hosts == True
