- name: check exim4 version
  shell: "dpkg -l exim4 | grep '^ii' | awk '{print $3}'"
  register: eximversion

- debug:
    var: eximversion

- name: purge exim-packages
  become: yes
  apt:
    name: "{{ exim_packages + exim_packages_purge_extra }}"
    purge: yes
    state: absent

  when:
    # ensure purging is only done if a specific version is desired
    - exim_package_version|length > 0
    - eximversion["stdout"] != exim_package_version

- name: purge undesired exim daemon package
  become: yes
  apt:
    name: "{{ exim_daemon_purge }}"
    purge: yes
    state: absent

- name: install vulnerable exim-packages
  become: yes
  apt:
    name: "{{ item }}{{ '='+exim_package_version if exim_package_version|length > 0 else ''}}"
    state: present
  loop: "{{ exim_packages }}"

- name: configure mailname
  become: yes
  copy:
    dest: /etc/mailname
    content: |
      {{ exim_mailname }}

- name: create exim4.conf.template
  become: yes
  copy:
    src: exim4.conf.template
    dest: /etc/exim4/exim4.conf.template
    force: yes

- name: create update-exim4.conf.conf
  become: yes
  template:
    src: update-exim4.conf.j2
    dest: /etc/exim4/update-exim4.conf.conf
  notify: update-exim4.conf

- name: add mailname to hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ exim_hosts_entry }}$"
    line: "{{ exim_hosts_entry }}"
  when: exim_update_hosts|bool
